### PR TITLE
Port code to Python3

### PR DESCRIPTION
**Pull request by antonkulaga**
I moved the code to python3 and used conda package of ANARCI instead of including it in the repository

### CODE REVIEW

**Comment by Francesco03** [comment]
Hello, 
thank you very much for updating this repository. 

Just a few comments:
1. While `micromamba `looks like a very interesting alternative since most of the user have anaconda installed I would not completely remove it. 
2. What if a user does not want to install `anaconda `or `micromamba`? I would keep the instructions to install the dependencies without anaconda or `micromamba`
3. In the paper the describes the protocol all the steps are designed according to the current status of the repository. If we are planning to update this code should we think about updating also the paper?

**Comment by amjjbonvin** [comment]
All very good points indeed!

We should keep the old instruction but also provide the new ones.
And I agree that `micromamba` is not mainstream. Better to provide anaconda instructions.

And in that way the paper is still in line with the repo.

**Comment by antonkulaga** [comment]
ok, so your suggestions: fallback to conda and keep pip-only instructions, anything else?
I actually plan to make a separate cli script that will run everything with one command

**Comment by amjjbonvin** [comment]
Yes - should be fine.

And we thus will have two sets of instructions, only more manual using pip and one using conda (the easiest way).

Also somewhere we should state the minimal python version

**Comment by antonkulaga** [comment]
Guys, I made changes according to your suggestions.

I also think that you have to publish the version that was used in the paper as a github release with corresponding stages. In such ways, those users who want to reproduce paper as-is will use that release, while the majority will use later release which is python 3 based. It is 2021, nobody uses python 2 anymore.

**Comment by amjjbonvin** [comment]
Thanks Anton

And good point - Francesco, I will create a release of the current version before merging this one.

**Review by amjjbonvin — COMMENTED** [review]
Your desciption / commands still involve micromamba instead of condo as we agreed upon.
Also why delete the HADDOCK PDB files as these are used. Or did I miss something?

**Comment by amjjbonvin** [comment]
PS: I also added the Zenodo DOI to the README file, which causes now a conflict. Please update your  version

**Comment by Francesco03** [comment]
Also the installation without anaconda seems missing to me. 

I also want to clarify that by the time I created this repository ANARCI was working only with python2.7. The updated ANARCI code compatible with python3 has been released only ~4 months ago.

**Comment by antonkulaga** [comment]
@amjjbonvin sorry, I did not notice there was an issue with the git push yesterday and README change was not included. Could you check now? At least in my branch readme is changed https://github.com/antonkulaga/HADDOCK-antibody-antigen

**Review by rvhonorato — CHANGES_REQUESTED** [review]
I resolved the conflicts and updated the CI for python3, @antonkulaga your edits had python3.10 and since it was just released [today](https://docs.python.org/3/whatsnew/3.10.html) there's still no support for it in our CI pipeline, so I downgraded it to 3.9, please confirm that it works as expected with this python version as well.

**Comment by antonkulaga** [comment]
@rvhonorato yes, 3.9 is ok. Please, let me know what is required from me

**Comment by rvhonorato** [comment]
All good then @antonkulaga, thanks for this edit!

**Comment by rvhonorato** [comment]
Tests are passing but would be good to run some examples just to double check before we merge this one @Francesco03 @amjjbonvin

**Comment by Francesco03** [comment]
Sure. Will do some tests in the coming days and accept the pull request if everything is ok. Thanks a lot!

**Comment by antonkulaga** [comment]
>Sure. Will do some tests in the coming days and accept the pull request if everything is ok. Thanks a lot!

@Francesco03 

Sorry, but I added one more commit to PR:
* I discovered a minor issue in requirements.txt and cli.py.
* I also updated cli.py to let it process either a file or a folder, it simplifies the lives of people like me that have many antibodies that require processing in the same way.

**Comment by antonkulaga** [comment]
Guys, please let me know what may be needed from my side to have this merged. 
I plan to add additional PR-s for other features after this one.

**Comment by Francesco03** [comment]
Code merged. Thank you very much for your contribution @antonkulaga.

**Pull request merged**
